CREATE TABLE
    books (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        title VARCHAR(50) NOT NULL,
        publish_date DATE NOT NULL,
        publisher VARCHAR(50) NOT NULL,
        cover_state VARCHAR(15) NOT NULL,
        label_id INT,
        source_id INT,
        author_id INT,
        genre_id INT
    );

ALTER TABLE books (
    CONSTRAINT fk_label FOREIGN KEY (label_id) REFERENCES labels (id),
    CONSTRAINT fk_source FOREIGN KEY (source_id) REFERENCES sources (id),
    CONSTRAINT fk_author FOREIGN KEY (label_id) REFERENCES authors (id),
    CONSTRAINT fk_genre FOREIGN KEY (label_id) REFERENCES genres (id)
);

CREATE TABLE
    labels (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        title VARCHAR(50) NOT NULL,
        color VARCHAR(50) NOT NULL
    );

CREATE TABLE
    games (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(50),
        multiplayer BOOLEAN NOT NULL,
        publish_date DATE NOT NULL,
        last_played_at DATE NOT NULL,
        genre_id INT,
        author_id INT,
        label_id INT,
        FOREIGN KEY (genre_id) REFERENCES genre (id),
        FOREIGN KEY (author_id) REFERENCES author (id),
        FOREIGN KEY (label_id) REFERENCES label (id),
        PRIMARY KEY (id)
    );

CREATE TABLE
    authors (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        first_name VARCHAR(50) NOT NULL,
        last_name VARCHAR(50) NOT NULL,
        PRIMARY KEY (id)
    );