CREATE TABLE books (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    publish_date DATE NOT NULL,
    publisher VARCHAR(50) NOT NULL,
    cover_state VARCHAR(15) NOT NULL,
    label_id INT,
    source_id INT,
    author_id INT,
    genre_id INT
);

ALTER TABLE books ADD CONSTRAINT fk_label FOREIGN KEY (label_id) REFERENCES labels(id);
ALTER TABLE books ADD CONSTRAINT fk_source FOREIGN KEY (source_id) REFERENCES sources(id);
ALTER TABLE books ADD CONSTRAINT fk_author FOREIGN KEY (label_id) REFERENCES authors(id);
ALTER TABLE books ADD CONSTRAINT fk_genre FOREIGN KEY (label_id) REFERENCES genres(id);

CREATE TABLE labels (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL
);