CREATE TABLE books (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    publish_date DATE NOT NULL,
    publisher VARCHAR(50) NOT NULL,
    cover_state VARCHAR(15) NOT NULL,
    label_id INT,
    author_id INT,
    genre_id INT
);

ALTER TABLE books (
    CONSTRAINT fk_label FOREIGN KEY (label_id) REFERENCES labels(id),
    CONSTRAINT fk_author FOREIGN KEY (label_id) REFERENCES authors(id),
    CONSTRAINT fk_genre FOREIGN KEY (label_id) REFERENCES genres(id)
);

CREATE TABLE labels (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL
);

CREATE TABLE MusicAlbum (
    id INT GENERATED ALWAYS AS IDENTITY,
    on_spotify BOOLEAN NOT NULL,
    publish_date DATE NOT NULL,
    genre_id INT NULL,
    author_id INT NULL,
    label_id INT NULL,
    FOREIGN KEY (genre_id) REFERENCES genre(id)
    FOREIGN KEY (author_id) REFERENCES author(id)
    FOREIGN KEY (label_id) REFERENCES label(id)
    archived BOOLEAN NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE genre (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);